// Tool opportunities mined from chat-histories/. Evidence is resolved from the JSON by build.mjs:
// `sessions` become the cadence strip, `snaps` pull real turns (by turn number or first regex match).

export const SIGNALS = {
  prime:  { label: "Re-priming",       def: "Same firm-context paste at the top of the session" },
  cadence:{ label: "Fixed cadence",    def: "Same job on a weekly or monthly rhythm with new inputs" },
  shape:  { label: "Repeated output",  def: "Same table, memo or scorecard shape re-specified each time" },
  rule:   { label: "Rule re-taught",   def: "A firm rule the assistant got wrong and had to be told again" },
  script: { label: "Script lost",      def: "A script written in chat, lost, and rebuilt worse" },
  paste:  { label: "Paste round-trip", def: "Export from a system, paste into chat, paste back into another" },
  drift:  { label: "Quality drift",    def: "Same request, different or wrong-shaped answer" },
};

export const OPPS = [
  {
    id: "clash-triage",
    name: "Clash triage & weekly issue report",
    kind: "Tool",
    who: ["Priya"],
    line: "Turn a raw Navisworks export into grouped issues, a New / Carried / Gone diff, a tracker CSV and the Monday agenda.",
    signals: ["prime", "cadence", "shape", "rule", "script", "paste"],
    cost: "28–38 h / week across three projects (cd-018)",
    repeats: [["Grouped issue table", "19× in 8 sessions"], ["Coordination email", "16× in 10 sessions"], ["Meeting agenda", "9× in 8 sessions"]],
    sessions: ["cd-003","cd-004","cd-005","cd-006","cd-008","cd-009","cd-011","cd-015","cd-016","cd-020"],
    snaps: [
      { sid: "cd-009", n: 2,  cap: "New / Carried / Gone diff, rebuilt by hand from HTML pasted into Excel" },
      { sid: "cd-004", n: 2,  cap: "Structural assigned the move, against the firm rule", flag: "Rule broken" },
      { sid: "cd-009", n: 10, cap: "Tracker CSV she pastes into her own spreadsheet" },
      { sid: "cd-009", n: 12, cap: "45-minute agenda, rebuilt every week" },
    ],
    plan: {
      inputs: ["Navisworks XML clash export (feet)", "Last week's grouped issue list", "Model upload log (filename, date)"],
      rules: ["Report by issue, never by raw clash", "IDs: PROJECT-LEVEL-DISCIPLINE PAIR-NN", "Ignore insulation clashes under 1/2\"", "Structural reviews, never owns the move", "Plenum under 10'-0\" AFF = P1; corridors need 8\" MEP clearance", "Stale = carried 6+ weeks; \"known / next model\" is not closure"],
      outputs: ["Grouped issue table with owner + reviewer", "New / Carried / Gone diff with stale flags", "Tracker CSV (issue_id, change, age_weeks, owner, next_action, agenda_order)", "Agenda at 45 or 15 minutes", "One email per consultant"],
      steps: ["Parser for the XML export, versioned in this repo, not in a chat", "Rule file the parser reads, editable by Priya", "Diff against last week's saved run", "Templates for agenda, CSV and consultant email"],
      effort: "M",
    },
  },
  {
    id: "close-pack",
    name: "Monthly close pack",
    kind: "Tool",
    who: ["Marcus"],
    line: "Clean the Vantagepoint export, compute earned fee and burn, and draft Wes's pack and Elena's page from one run.",
    signals: ["prime", "cadence", "shape", "rule", "script", "drift"],
    cost: "3.0 days direct, 3.5 elapsed, every month (fin-017)",
    repeats: [["13-week cash-flow table", "16× in 12 sessions"], ["WIP / RAG table", "12× in 8 sessions"], ["Elena one-page version", "11× in 8 sessions"]],
    sessions: ["fin-003","fin-005","fin-008","fin-010","fin-013","fin-016","fin-018","fin-020"],
    snaps: [
      { sid: "fin-005", n: 2, cap: "April close: WIP RAG table" },
      { sid: "fin-008", n: 2, cap: "May close: the same table, new numbers" },
      { sid: "fin-008", match: /Check the total/, role: "user", cap: "Marcus catches a wrong total", flag: "Arithmetic error" },
    ],
    plan: {
      inputs: ["Vantagepoint WIP export (CSV)", "Late-timesheet list", "AR aging", "PM percent-complete notes"],
      rules: ["Net revenue = gross − consultants − reimbursables", "Never a multiplier on gross", "Cut at Friday week-ending; FY ends Dec 31", "$000, no cents", "Burn: red >105%, amber 95–105%, green <95%", "Label every figure actual, forecast or PM judgment"],
      outputs: ["WIP RAG table by project and phase", "Earned fee = contract × % complete; burn = spent ÷ earned", "Wes narrative, five bullets with owners", "Elena page: cash first, then backlog"],
      steps: ["Export cleaner that tolerates column drift", "Totals computed in code, never by the model", "Pack templates for Wes and Elena", "Pre-close checklist: timesheets, reimbursables, phase coding, AR backup"],
      effort: "M",
    },
  },
  {
    id: "vendor-scorecard",
    name: "Vendor intake & scorecard",
    kind: "Tool",
    who: ["Dana"],
    line: "Tier the vendor from its answers, score six categories with weights, list the gaps and draft the follow-up questions.",
    signals: ["prime", "shape", "rule", "paste"],
    cost: "One grind session per vendor, 14 vendors in 6 months",
    repeats: [["Follow-up question list", "25× in 14 sessions"], ["Six-category scorecard", "16× in 14 sessions"], ["Memo / email to owner", "20× in 13 sessions"]],
    sessions: ["ven-002","ven-003","ven-004","ven-005","ven-007","ven-009","ven-010","ven-011","ven-012","ven-013","ven-014","ven-016","ven-017","ven-020"],
    snaps: [
      { sid: "ven-002", n: 8,  cap: "Six-category scorecard, second attempt after Dana downgraded Security" },
      { sid: "ven-009", match: /You did it again/, role: "user", cap: "Desktop add-in tiered as Tier 2, twice", flag: "Rule broken" },
      { sid: "ven-002", n: 10, cap: "Pointed follow-up questions" },
      { sid: "ven-002", n: 12, cap: "Recommendation memo to Sandeep and Wes" },
    ],
    plan: {
      inputs: ["Vendor questionnaire answers or trust-center text", "Contract / DPA excerpts", "Requesting project and owner"],
      rules: ["Tier 1 = touches project models or client data, even desktop-only", "Tier 1 needs SOC 2 Type II or ISO 27001, a DPA, $2M cyber, HRA additional insured", "AI tools need contractual no-training", "Non-US storage needs Wes's sign-off"],
      outputs: ["Tier with the reason", "Scorecard: Security, Data & Privacy, Legal & Insurance, Operational Fit, Commercial, References (1–5, weighted)", "Go / Go with conditions / No", "Follow-up questions, memo, tracker line"],
      steps: ["Intake form that captures answers once", "Tier gate evaluated from answers, not from chat", "Scorecard template with fixed weights", "Writes the tracker line to the register"],
      effort: "S",
    },
  },
  {
    id: "submittal-comments",
    name: "Submittal review comments",
    kind: "Tool",
    who: ["Tomás"],
    line: "Batch a submittal package into paragraph-numbered comments with a status and routing, instead of pasting it one chunk at a time.",
    signals: ["prime", "cadence", "shape", "paste", "drift"],
    cost: "11 h / week of admin before any technical review (spec-020)",
    repeats: [["Paragraph-numbered comment", "76× in 9 sessions"], ["\"Same exercise, next chunk\" paste", "most turns in 9 sessions"]],
    sessions: ["spec-003","spec-009","spec-011","spec-012","spec-013","spec-015","spec-018","spec-019","spec-020"],
    snaps: [
      { sid: "spec-012", n: 4, cap: "Comment 2 of a 41-item Kestrel Friday dump" },
      { sid: "spec-009", n: 2, cap: "Bid-night bracket hunt answered with the submittal-comment template", flag: "Wrong output" },
    ],
    plan: {
      inputs: ["Procore submittal batch (PDF + metadata)", "Spec sections in Specpoint", "Consultant routing table"],
      rules: ["Every comment cites section and paragraph", "22 / 23 / 26 go to Pemberton unless stated", "Review period runs from complete receipt, not batch upload", "Comment, never a rewrite or design direction"],
      outputs: ["Status per item (Approved, Approved as noted, Revise and resubmit, N/A)", "Numbered comments ready for Procore / Bluebeam", "Routing notes to Sturgis or Pemberton", "Turnaround log by received date"],
      steps: ["Batch intake from a Procore export", "Section lookup against the project manual", "Comment generator with house rules", "Turnaround metrics for Elena's page"],
      effort: "M",
    },
  },
  {
    id: "one-pager",
    name: "Elena one-pager composer",
    kind: "Template",
    who: ["Priya", "Marcus", "Dana", "Tomás"],
    line: "One page per discipline in Elena's format, fed by each tool's numbers, with the confidence caveat built in.",
    signals: ["cadence", "shape", "rule"],
    cost: "All four wrote one on 9 Sep; Marcus writes one every close",
    repeats: [["Elena page", "every close + 4 on 9 Sep"], ["Tiny scorecard / 4-row table", "in 3 of the 4 quarterly pages"]],
    sessions: ["fin-003","cd-009","fin-005","fin-008","fin-018","cd-019","ven-019","spec-019"],
    snaps: [
      { sid: "cd-019", n: 4, cap: "Coordination health, 9 Sep" },
      { sid: "ven-019", n: 6, cap: "Third-party risk: the four-row table Elena allows" },
    ],
    plan: {
      inputs: ["Numbers from the clash, close, vendor and submittal tools", "Discipline owner's notes"],
      rules: ["One page, printable, ≤170 words of narrative", "No spreadsheets; one tiny scorecard at most", "Lead with the answer, then the ask", "State data confidence without sounding fake", "Don't open with Red overall"],
      outputs: ["Discipline page in a shared layout", "\"What would make this green\" answers by project", "Principals' ask, stated plainly"],
      steps: ["Shared page template in Modul", "Slots each tool fills automatically", "Word-count and format checks"],
      effort: "S",
    },
  },
  {
    id: "firm-context",
    name: "Firm context profile",
    kind: "Foundation",
    who: ["Priya", "Marcus", "Dana", "Tomás"],
    line: "Store each role's context and rules once so no session starts with a 90-word paste.",
    signals: ["prime", "rule"],
    cost: "67 of 80 sessions open with a paste; about 6,400 words retyped",
    repeats: [["Opening context paste", "Priya 18 · Marcus 15 · Dana 14 · Tomás 20 of 20"]],
    sessions: "@prime",
    snaps: [
      { sid: "cd-001", n: 1, role: "user", para: 1, cap: "Priya's paste, in 18 of 20 sessions" },
      { sid: "fin-001", n: 1, role: "user", para: 1, cap: "Marcus's paste, in 15 of 20" },
      { sid: "ven-002", n: 1, role: "user", para: 1, cap: "Dana's paste, in 14 of 20" },
      { sid: "spec-001", n: 1, role: "user", para: 1, cap: "Tomás's paste, in 20 of 20" },
    ],
    plan: {
      inputs: ["The four pastes as they stand in September", "Corrections users made mid-session"],
      rules: ["One profile per role, owned by that person", "Rules are testable statements, not prose", "Every tool above reads from it"],
      outputs: ["Role profiles: Priya, Marcus, Dana, Tomás", "Shared firm facts (projects, consultants, milestones)"],
      steps: ["Extract rules from the pastes and the corrections", "Store as a skill or project memory", "Wire into each tool"],
      effort: "S",
    },
  },
  {
    id: "spec-qa",
    name: "Spec section QA",
    kind: "Tool",
    who: ["Tomás"],
    line: "Lint a Specpoint section for house rules, empty brackets, broken cross-references and unverified standards before issue.",
    signals: ["prime", "rule", "drift", "script"],
    cost: "Night-before-bid hunts (spec-008, spec-009)",
    repeats: [["Section cleanup pass", "7 sessions before 75% CD and bid set"]],
    sessions: ["spec-001","spec-002","spec-003","spec-004","spec-007","spec-008","spec-009"],
    snaps: [
      { sid: "spec-003", match: /cannot verify standards/, role: "user", cap: "A made-up ASTM caught late", flag: "Hallucination" },
      { sid: "spec-001", n: 4, cap: "Air barrier section rewritten in SectionFormat" },
    ],
    plan: {
      inputs: ["Section export from Specpoint", "Previous issued version for diff"],
      rules: ["\"Provide\", never \"shall be\" in Part 2", "No single manufacturer without \"or comparable product\"", "Three-part SectionFormat only", "Standards must exist in current MasterSpec; never invented"],
      outputs: ["Findings list by paragraph", "Empty [ ] choices and {cross-references}", "Version diff", "Superseded standard flags"],
      steps: ["Regex checks for brackets, tense, manufacturers", "Standards list from MasterSpec, checked not generated", "Diff between issued versions"],
      effort: "S",
    },
  },
  {
    id: "submittal-register",
    name: "Submittal register export",
    kind: "Tool",
    who: ["Tomás"],
    line: "Build the register from the project manual in the exact tab-separated format Procore accepts.",
    signals: ["prime", "shape", "script", "paste"],
    cost: "Format lost and rebuilt (spec-011)",
    repeats: [["Register rows", "9× in 8 sessions"]],
    sessions: ["spec-001","spec-002","spec-006","spec-011"],
    snaps: [
      { sid: "spec-011", n: 4, cap: "Tab-separated register after commas broke the notes" },
      { sid: "spec-001", n: 8, cap: "The same register as a markdown table, March" },
    ],
    plan: {
      inputs: ["Project manual sections (Part 1 submittal paragraphs)"],
      rules: ["Tab-separated; notes contain commas", "Ball-in-court: HRA, Sturgis, Pemberton, GC, Consultant only", "Action / Informational / Closeout types"],
      outputs: ["Register TSV for Excel and Procore", "Due triggers per item"],
      steps: ["Parse Part 1 submittal paragraphs", "Fixed column schema saved in the repo", "Export button, no chat"],
      effort: "S",
    },
  },
  {
    id: "vendor-register",
    name: "Vendor register",
    kind: "Tool",
    who: ["Dana"],
    line: "One deduplicated list of active vendors with tier, evidence gaps and renewal dates, so the count stops moving.",
    signals: ["shape", "paste", "cadence"],
    cost: "Count moved between 68 and 74 before the board review",
    repeats: [["Register table", "rebuilt in 3 sessions"], ["Tracker line", "end of most scorecard sessions"]],
    sessions: ["ven-001","ven-014","ven-018","ven-019"],
    snaps: [
      { sid: "ven-019", n: 6, cap: "Posture table for the principals" },
      { sid: "ven-018", match: /112 names/, role: "user", cap: "Five sources, duplicates everywhere", flag: "Count unclear" },
    ],
    plan: {
      inputs: ["AP export, IT subscriptions, project vendor folders, consultant list, COI folder"],
      rules: ["Active vendor = paid or under contract in the last 12 months", "Tier from the scorecard tool", "Tier 1 with any missing evidence = high risk"],
      outputs: ["Deduplicated register with vendor IDs", "Open Tier 1 gates", "Renewals in the next 90 days with owners"],
      steps: ["Name matching across sources", "Monthly review view", "Feeds the one-pager"],
      effort: "M",
    },
  },
];
